import { SITE } from '../constants/site.ts';
import { useInvoiceContext } from '../context/InvoiceContext';

const fmt = (n) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(n);

function calcTax({ items, taxSettings, senderDetails, clientDetails }) {
  const subtotal = items.reduce((s, i) => s + i.rate * i.quantity, 0);
  const isInter = (taxSettings.senderState || '').toLowerCase() !== (clientDetails.state || '').toLowerCase();
  let cgst = 0, sgst = 0, igst = 0;
  if (taxSettings.applyGst && taxSettings.gstRate) {
    if (isInter && clientDetails.state) igst = subtotal * (taxSettings.gstRate / 100);
    else {
      cgst = subtotal * ((taxSettings.gstRate / 2) / 100);
      sgst = subtotal * ((taxSettings.gstRate / 2) / 100);
    }
  }
  return { subtotal, cgst, sgst, igst, isInter, grand: subtotal + cgst + sgst + igst };
}

// Status badge with inline hex colors (safe for PDF)
const StatusBadge = ({ status }) => {
  const colors = {
    Paid: { bg: '#16a34a', text: '#fff' },
    Unpaid: { bg: '#dc2626', text: '#fff' },
    Partial: { bg: '#d97706', text: '#fff' },
  };
  const c = colors[status] || colors.Unpaid;
  return (
    <span style={{
      backgroundColor: c.bg,
      color: c.text,
      padding: '1px 7px',
      borderRadius: 3,
      fontSize: 11,
      fontWeight: 700,
      display: 'inline-block',
      verticalAlign: 'middle',
      lineHeight: '18px',
    }}>
      {status}
    </span>
  );
};

// ── Shared bottom: Payment + Declaration + Signature + Invoy footer ────
function InvoiceBottom({ senderDetails, contentOptions, paymentDetails, declaration }) {
  return (
    <>
      {(contentOptions.showPaymentDetails || contentOptions.showDeclaration || contentOptions.showSignature) && (
        <div style={{ borderTop: '1px solid #e5e7eb', marginTop: 24, paddingTop: 16 }} />
      )}

      {contentOptions.showPaymentDetails && (
        <div style={{ marginBottom: 16 }}>
          <p style={{ fontWeight: 700, fontSize: 13, color: '#1f2937', marginBottom: 6 }}>Payment Details</p>
          <p style={{ fontSize: 13, color: '#374151', margin: 0, lineHeight: 2 }}>
            {paymentDetails.mode && <><span style={{ color: '#6b7280' }}>Mode:</span> {paymentDetails.mode}&nbsp;&nbsp;&nbsp;</>}
            <span style={{ color: '#6b7280' }}>Status:</span> <StatusBadge status={paymentDetails.status} />
            {paymentDetails.transactionId && <>&nbsp;&nbsp;&nbsp;<span style={{ color: '#6b7280' }}>Transaction ID:</span> <strong>{paymentDetails.transactionId}</strong></>}
          </p>
        </div>
      )}

      {(contentOptions.showDeclaration || contentOptions.showSignature) && (
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 24, marginTop: 16 }}>
          {contentOptions.showDeclaration && (
            <div style={{ flex: 1 }}>
              <p style={{ fontWeight: 700, fontSize: 12, color: '#1f2937', marginBottom: 6 }}>Declaration</p>
              <ul style={{ paddingLeft: 16, margin: 0 }}>
                {(declaration || '').split('\n').filter(Boolean).map((line, i) => (
                  <li key={i} style={{ fontSize: 11, color: '#4b5563', marginBottom: 3 }}>{line.replace(/^\d+\.\s*/, '')}</li>
                ))}
              </ul>
            </div>
          )}

          {contentOptions.showSignature && (
            <div style={{ minWidth: 160, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
              <p style={{ fontSize: 11, fontWeight: 700, color: '#1f2937', alignSelf: 'flex-start', marginBottom: 12 }}>Authorised Signature</p>
              {senderDetails.signature
                ? <img src={senderDetails.signature} alt="Signature" style={{ height: 56, objectFit: 'contain', marginBottom: 8 }} />
                : <div style={{ height: 56, width: '100%', border: '1px dashed #d1d5db', borderRadius: 4, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 8 }}>
                  <span style={{ fontSize: 10, color: '#9ca3af', fontStyle: 'italic' }}>Signature</span>
                </div>
              }
              <div style={{ width: '100%', borderTop: '1px solid #9ca3af', paddingTop: 4, textAlign: 'center', fontSize: 11, fontWeight: 600, color: '#1f2937' }}>
                {senderDetails.businessName || senderDetails.name || 'Authorised Signatory'}
              </div>
            </div>
          )}
        </div>
      )}
    </>
  );
}

// ── Invoy branded footer ───────────────────────────────────────────────
const InvoyFooter = () => (
  <div style={{ borderTop: '1px solid #e5e7eb', marginTop: 32, paddingTop: 12, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
    <span style={{ fontSize: 11, color: '#9ca3af' }}>Thank you for your business!</span>
    <span style={{ fontSize: 11, color: '#9ca3af', fontWeight: 500 }}>
      Generated by https://invoy.in
    </span>
  </div>
);

// ══════════════════════════════════════════════════════════════════════════
// CLASSIC TEMPLATE
// ══════════════════════════════════════════════════════════════════════════
function ClassicTemplate({ senderDetails, clientDetails, invoiceMeta, items, taxSettings, contentOptions, paymentDetails, declaration }) {
  const { subtotal, cgst, sgst, igst, isInter, grand } = calcTax({ items, taxSettings, senderDetails, clientDetails });

  return (
    <div id="invoice-preview-container" style={{ backgroundColor: '#fff', color: '#000', padding: 32, minHeight: 1056, width: '100%', fontFamily: 'Arial, sans-serif', border: '1px solid #e5e7eb', position: 'relative' }}>

      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          {senderDetails.logo && <img src={senderDetails.logo} alt="logo" style={{ height: 48, objectFit: 'contain' }} />}
          <h1 style={{ fontSize: 22, fontWeight: 800, letterSpacing: 3, color: '#1B365D', textTransform: 'uppercase', margin: 0 }}>
            {senderDetails.businessName || senderDetails.name || 'YOUR COMPANY'}
          </h1>
        </div>
        <div style={{ display: 'flex', gap: 16, alignItems: 'center' }}>
          <div style={{ fontSize: 10, fontWeight: 700, textAlign: 'center', lineHeight: 1.4, color: '#374151' }}>
            <div style={{ fontSize: 18, marginBottom: 2 }}>🏛️</div>GOVT OF INDIA
          </div>
          <div style={{ fontSize: 10, fontWeight: 700, textAlign: 'center', lineHeight: 1.4, color: '#1B365D', borderLeft: '1px solid #d1d5db', paddingLeft: 16 }}>
            <div style={{ fontSize: 20, fontWeight: 900, letterSpacing: -1 }}>MSME</div>
            MICRO, SMALL &amp; MEDIUM ENTERPRISES
          </div>
        </div>
      </div>

      {/* Title bar */}
      <div style={{ backgroundColor: '#4472C4', color: '#fff', padding: '8px 24px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <h2 style={{ fontSize: 16, fontWeight: 600, letterSpacing: 1, margin: 0 }}>TAX INVOICE</h2>
        <span style={{ fontWeight: 600 }}>📄 {invoiceMeta.invoiceNumber || 'INV-000'}</span>
      </div>

      {/* Invoice meta */}
      <div style={{ display: 'flex', justifyContent: 'space-between', padding: '0 8px', marginBottom: 24, fontSize: 13, fontWeight: 600, color: '#1f2937' }}>
        <span>Invoice No: <span style={{ color: '#4472C4', fontWeight: 400 }}>{invoiceMeta.invoiceNumber || 'INV-000'}</span></span>
        <span>Date: <span style={{ fontWeight: 400 }}>{invoiceMeta.date || 'N/A'}</span></span>
        {invoiceMeta.dueDate && <span>Due: <span style={{ fontWeight: 400 }}>{invoiceMeta.dueDate}</span></span>}
      </div>

      {/* FROM / TO */}
      <div style={{ display: 'flex', borderTop: '1px solid #e5e7eb', borderBottom: '1px solid #e5e7eb', marginBottom: 24 }}>
        <div style={{ width: '50%', padding: '20px 20px', borderRight: '1px solid #e5e7eb' }}>
          <p style={{ fontWeight: 700, fontSize: 11, textTransform: 'uppercase', letterSpacing: 2, color: '#374151', marginBottom: 10 }}>From</p>
          <div style={{ fontSize: 13, lineHeight: 1.8, color: '#1f2937' }}>
            {senderDetails.name && <p style={{ margin: 0 }}><span style={{ color: '#6b7280' }}>Name:</span> {senderDetails.name}</p>}
            {senderDetails.gstin && <p style={{ margin: 0 }}><span style={{ color: '#6b7280' }}>GSTIN:</span> <strong>{senderDetails.gstin}</strong></p>}
            {senderDetails.udyamNo && <p style={{ margin: 0 }}><span style={{ color: '#6b7280' }}>Udyam:</span> {senderDetails.udyamNo}</p>}
            {senderDetails.address && <p style={{ margin: 0 }}><span style={{ color: '#6b7280' }}>Address:</span> {senderDetails.address}</p>}
            {senderDetails.email && <p style={{ margin: 0 }}><span style={{ color: '#6b7280' }}>Email:</span> {senderDetails.email}</p>}
            {senderDetails.phone && <p style={{ margin: 0 }}><span style={{ color: '#6b7280' }}>Phone:</span> {senderDetails.phone}</p>}
          </div>
        </div>
        <div style={{ width: '50%', padding: '20px 20px' }}>
          <p style={{ fontWeight: 700, fontSize: 11, textTransform: 'uppercase', letterSpacing: 2, color: '#374151', marginBottom: 10 }}>Billed To</p>
          <div style={{ fontSize: 13, lineHeight: 1.8, color: '#1f2937' }}>
            <p style={{ margin: 0, fontWeight: 700, fontSize: 15 }}>{clientDetails.name || 'Client Name'}</p>
            {clientDetails.address && <p style={{ margin: 0, color: '#374151' }}>{clientDetails.address}</p>}
            {clientDetails.email && <p style={{ margin: 0, color: '#374151' }}>{clientDetails.email}</p>}
            {clientDetails.state && <p style={{ margin: 0, color: '#6b7280', fontSize: 11 }}>State: {clientDetails.state}</p>}
          </div>
        </div>
      </div>

      {/* Table */}
      <div style={{ border: '1px solid #d1d5db', marginBottom: 24 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
          <thead>
            <tr style={{ backgroundColor: '#4472C4', color: '#fff', fontSize: 13 }}>
              <th style={{ padding: '10px 16px', fontWeight: 600, width: '55%' }}>Service / Description</th>
              <th style={{ padding: '10px 16px', fontWeight: 600, textAlign: 'center', width: 60 }}>Qty</th>
              <th style={{ padding: '10px 16px', fontWeight: 600, textAlign: 'right' }}>Rate</th>
              <th style={{ padding: '10px 16px', fontWeight: 600, textAlign: 'right' }}>Amount</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item, i) => (
              <tr key={item.id} style={{ borderBottom: '1px solid #e5e7eb', backgroundColor: i % 2 === 0 ? '#fff' : '#fafafa' }}>
                <td style={{ padding: '12px 16px', fontSize: 13, color: '#1f2937' }}>{item.description || '-'}</td>
                <td style={{ padding: '12px 16px', fontSize: 13, textAlign: 'center', color: '#1f2937' }}>{item.quantity}</td>
                <td style={{ padding: '12px 16px', fontSize: 13, textAlign: 'right', color: '#1f2937' }}>{fmt(item.rate)}</td>
                <td style={{ padding: '12px 16px', fontSize: 13, textAlign: 'right', fontWeight: 600, color: '#111827' }}>{fmt(item.quantity * item.rate)}</td>
              </tr>
            ))}
            <tr style={{ backgroundColor: '#f9fafb', borderTop: '1px solid #d1d5db' }}>
              <td colSpan={3} style={{ padding: '8px 16px', textAlign: 'right', fontSize: 13, color: '#4b5563', fontWeight: 500 }}>Subtotal</td>
              <td style={{ padding: '8px 16px', textAlign: 'right', fontWeight: 600, fontSize: 13 }}>{fmt(subtotal)}</td>
            </tr>
            {taxSettings.applyGst && isInter && (
              <tr style={{ borderTop: '1px solid #e5e7eb' }}>
                <td colSpan={3} style={{ padding: '8px 16px', textAlign: 'right', fontSize: 13, color: '#4b5563' }}>IGST ({taxSettings.gstRate}%)</td>
                <td style={{ padding: '8px 16px', textAlign: 'right', fontWeight: 500, fontSize: 13 }}>{fmt(igst)}</td>
              </tr>
            )}
            {taxSettings.applyGst && !isInter && (<>
              <tr style={{ borderTop: '1px solid #e5e7eb' }}>
                <td colSpan={3} style={{ padding: '8px 16px', textAlign: 'right', fontSize: 13, color: '#4b5563' }}>CGST ({taxSettings.gstRate / 2}%)</td>
                <td style={{ padding: '8px 16px', textAlign: 'right', fontWeight: 500, fontSize: 13 }}>{fmt(cgst)}</td>
              </tr>
              <tr>
                <td colSpan={3} style={{ padding: '8px 16px', textAlign: 'right', fontSize: 13, color: '#4b5563' }}>SGST ({taxSettings.gstRate / 2}%)</td>
                <td style={{ padding: '8px 16px', textAlign: 'right', fontWeight: 500, fontSize: 13 }}>{fmt(sgst)}</td>
              </tr>
            </>)}
          </tbody>
        </table>
        <div style={{ background: 'linear-gradient(to right, #4472C4, #2a56a8)', color: '#fff', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px' }}>
          <span style={{ fontWeight: 600, fontSize: 16 }}>Total Amount</span>
          <span style={{ fontWeight: 800, fontSize: 18 }}>{fmt(grand)}</span>
        </div>
      </div>

      <InvoiceBottom senderDetails={senderDetails} contentOptions={contentOptions} paymentDetails={paymentDetails} declaration={declaration} />
      <InvoyFooter />
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════
// MODERN TEMPLATE
// ══════════════════════════════════════════════════════════════════════════
function ModernTemplate({ senderDetails, clientDetails, invoiceMeta, items, taxSettings, contentOptions, paymentDetails, declaration }) {
  const { subtotal, cgst, sgst, igst, isInter, grand } = calcTax({ items, taxSettings, senderDetails, clientDetails });

  return (
    <div id="invoice-preview-container" style={{ backgroundColor: '#fff', color: '#000', padding: 40, minHeight: 1056, width: '100%', fontFamily: 'Arial, sans-serif', position: 'relative' }}>

      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 40 }}>
        <div>
          {senderDetails.logo && <img src={senderDetails.logo} alt="logo" style={{ height: 56, objectFit: 'contain', marginBottom: 12 }} />}
          <h1 style={{ fontSize: 36, fontWeight: 900, color: '#111827', textTransform: 'uppercase', letterSpacing: -1, margin: 0 }}>INVOICE</h1>
          <p style={{ color: '#9ca3af', fontSize: 13, fontWeight: 500, margin: '4px 0 0' }}>#{invoiceMeta.invoiceNumber || 'INV-000'}</p>
        </div>
        <div style={{ textAlign: 'right' }}>
          <h2 style={{ fontSize: 18, fontWeight: 800, color: '#111827', margin: '0 0 4px' }}>{senderDetails.businessName || senderDetails.name || 'Your Company'}</h2>
          {senderDetails.businessName && senderDetails.name && <p style={{ fontSize: 13, color: '#4b5563', margin: '0 0 2px' }}>{senderDetails.name}</p>}
          {senderDetails.address && <p style={{ fontSize: 12, color: '#6b7280', margin: '2px 0', maxWidth: 220 }}>{senderDetails.address}</p>}
          {senderDetails.email && <p style={{ fontSize: 12, color: '#6b7280', margin: '2px 0' }}>{senderDetails.email}</p>}
          {senderDetails.phone && <p style={{ fontSize: 12, color: '#6b7280', margin: '2px 0' }}>{senderDetails.phone}</p>}
          {senderDetails.gstin && <p style={{ fontSize: 11, fontWeight: 700, color: '#374151', margin: '4px 0 0', backgroundColor: '#f3f4f6', padding: '2px 8px', borderRadius: 4, display: 'inline-block' }}>GSTIN: {senderDetails.gstin}</p>}
          {senderDetails.udyamNo && <p style={{ fontSize: 11, color: '#6b7280', margin: '2px 0' }}>Udyam: {senderDetails.udyamNo}</p>}
        </div>
      </div>

      <div style={{ borderTop: '2px solid #111827', marginBottom: 32 }} />

      {/* Billed To + Dates */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 40 }}>
        <div>
          <p style={{ fontSize: 10, fontWeight: 800, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 3, margin: '0 0 8px' }}>Billed To</p>
          <h3 style={{ fontSize: 16, fontWeight: 700, color: '#1f2937', margin: '0 0 4px' }}>{clientDetails.name || 'Client Name'}</h3>
          {clientDetails.address && <p style={{ fontSize: 12, color: '#6b7280', margin: '2px 0' }}>{clientDetails.address}</p>}
          {clientDetails.email && <p style={{ fontSize: 12, color: '#6b7280', margin: '2px 0' }}>{clientDetails.email}</p>}
          {clientDetails.state && <p style={{ fontSize: 11, color: '#9ca3af', margin: '4px 0 0' }}>State of Supply: <strong style={{ color: '#4b5563' }}>{clientDetails.state}</strong></p>}
        </div>
        <div style={{ textAlign: 'right' }}>
          <p style={{ fontSize: 13, color: '#1f2937', margin: '0 0 6px' }}><span style={{ color: '#6b7280' }}>Invoice Date:</span> <strong>{invoiceMeta.date || 'N/A'}</strong></p>
          {invoiceMeta.dueDate && <p style={{ fontSize: 13, color: '#1f2937', margin: 0 }}><span style={{ color: '#6b7280' }}>Due Date:</span> <strong>{invoiceMeta.dueDate}</strong></p>}
        </div>
      </div>

      {/* Items Table */}
      <div style={{ marginBottom: 32 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
          <thead>
            <tr style={{ borderBottom: '2px solid #111827' }}>
              <th style={{ padding: '10px 8px', fontSize: 11, fontWeight: 800, color: '#1f2937', textTransform: 'uppercase', letterSpacing: 1 }}>Description</th>
              <th style={{ padding: '10px 8px', fontSize: 11, fontWeight: 800, color: '#1f2937', textTransform: 'uppercase', letterSpacing: 1, textAlign: 'center', width: 80 }}>Qty</th>
              <th style={{ padding: '10px 8px', fontSize: 11, fontWeight: 800, color: '#1f2937', textTransform: 'uppercase', letterSpacing: 1, textAlign: 'right', width: 110 }}>Rate</th>
              <th style={{ padding: '10px 8px', fontSize: 11, fontWeight: 800, color: '#1f2937', textTransform: 'uppercase', letterSpacing: 1, textAlign: 'right', width: 110 }}>Amount</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id} style={{ borderBottom: '1px solid #f3f4f6' }}>
                <td style={{ padding: '14px 8px', fontSize: 13, color: '#1f2937' }}>{item.description || '-'}</td>
                <td style={{ padding: '14px 8px', fontSize: 13, color: '#1f2937', textAlign: 'center' }}>{item.quantity}</td>
                <td style={{ padding: '14px 8px', fontSize: 13, color: '#1f2937', textAlign: 'right' }}>{fmt(item.rate)}</td>
                <td style={{ padding: '14px 8px', fontSize: 13, fontWeight: 600, color: '#111827', textAlign: 'right' }}>{fmt(item.quantity * item.rate)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Totals */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 32 }}>
        <div style={{ width: 256 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, color: '#4b5563', marginBottom: 8 }}>
            <span>Subtotal</span><span style={{ fontWeight: 500, color: '#1f2937' }}>{fmt(subtotal)}</span>
          </div>
          {taxSettings.applyGst && isInter && (
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, color: '#4b5563', marginBottom: 8 }}>
              <span>IGST ({taxSettings.gstRate}%)</span><span style={{ fontWeight: 500, color: '#1f2937' }}>{fmt(igst)}</span>
            </div>
          )}
          {taxSettings.applyGst && !isInter && (<>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, color: '#4b5563', marginBottom: 8 }}>
              <span>CGST ({taxSettings.gstRate / 2}%)</span><span style={{ fontWeight: 500, color: '#1f2937' }}>{fmt(cgst)}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, color: '#4b5563', marginBottom: 8 }}>
              <span>SGST ({taxSettings.gstRate / 2}%)</span><span style={{ fontWeight: 500, color: '#1f2937' }}>{fmt(sgst)}</span>
            </div>
          </>)}
          <div style={{ borderTop: '2px solid #111827', paddingTop: 12, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontWeight: 900, fontSize: 18, color: '#111827' }}>Total</span>
            <span style={{ fontWeight: 900, fontSize: 20, color: '#111827' }}>{fmt(grand)}</span>
          </div>
        </div>
      </div>

      <InvoiceBottom senderDetails={senderDetails} contentOptions={contentOptions} paymentDetails={paymentDetails} declaration={declaration} />
      <InvoyFooter />
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════
// EXPORT
// ══════════════════════════════════════════════════════════════════════════
export default function InvoicePreview() {
  const { data } = useInvoiceContext();
  if (data.template === 'classic') return <ClassicTemplate {...data} />;
  return <ModernTemplate {...data} />;
}
